stages:
  - requirements
  - test
  - deploy

install requirements:
  stage: requirements
  variables:
    JEKYLL_ENV: production
    LC_ALL: C.UTF-8
  script:
    - bundle install --path=${HOME}/.gems
  only:
    - master
  tags:
    - penguin

run tests:
  stage: test
  variables:
    JEKYLL_ENV: production
    LC_ALL: C.UTF-8
  script:
    - bundle exec jekyll build -d test
  only:
    - master
  tags:
    - penguin

pages:
  stage: deploy
  variables:
    JEKYLL_ENV: production
    LC_ALL: C.UTF-8
  script:
    - bundle exec jekyll build
    - /usr/bin/sudo -u deploy rsync --archive /srv/www/org_gtalug_board/html/
  only:
    - master
  tags:
    - penguin
