image: ruby:2.4

variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8
  GEM_HOME: ${HOME}/.gems



test:
  stage: test
  variables:
    JEKYLL_ENV: production
    LC_ALL: C.UTF-8
    GEM_HOME: ${HOME}/.gems
  before_script:
    - bundle install
  script:
    - bundle exec jekyll build -d test
  artifacts:
    paths:
      - test
  except:
    - master
  tags:
    - penguin

pages:
  stage: deploy
  variables:
    JEKYLL_ENV: production
    LC_ALL: C.UTF-8
    GEM_HOME: ${HOME}/.gems
  script:
    - bundle exec jekyll build
    - /usr/bin/sudo -u deploy rsync --archive /src/www/org_gtalug_board/html/
  only:
    - master
  tags:
    - penguin
