stages:
    - test
    - deploy

variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8

before_script:
  - bundle install --path=${HOME}/.gems

test:
  stage: test
  script:
    - bundle exec jekyll build -d test
  artifacts:
    paths:
      - test
  except:
    - master
  tags:
    - penguin

pages:
  stage: deploy
  script:
    - bundle exec jekyll build
    - /usr/bin/sudo -u deploy rsync --archive /srv/www/org_gtalug_board/html/
  only:
    - master
  tags:
    - penguin
