stages:
  - test
  - deploy

run tests:
  stage: test
  variables:
    JEKYLL_ENV: production
    LC_ALL: C.UTF-8
  before_script:
    - bundle install --path=${HOME}/.gems
  script:
    - bundle exec jekyll build -d test
  only:
    - master
  tags:
    - penguin

deploy to website:
  stage: deploy
  variables:
    JEKYLL_ENV: production
    LC_ALL: C.UTF-8
  before_script:
    - bundle install --path=${HOME}/.gems
  script:
    - bundle exec jekyll build
    - /usr/bin/sudo -u deploy rsync --archive _site/ /srv/www/org_gtalug_board/html/
  only:
    - master
  tags:
    - penguin
