image: ruby:2.4

variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8
  GEM_HOME: ${HOME}/.gems

before_script:
  - bundle install

test:
  stage: test
  script:
    - bundle exec jekyll build -d test
  artifacts:
    paths:
      - test
  except:
    - master
  tags:
    - penguin

pages:
  stage: deploy
  script:
    - bundle exec jekyll build
    - /usr/bin/sudo -u deploy rsync --archive /src/www/org_gtalug_board/html/
  only:
    - master
  tags:
    - penguin
