* 28th April, 2014

** Upcoming Meetings

- May ::  Movie Magic: The Art of Visual Effects with Ahmed Shehata 

- June :: TBA

- July :: TBA

** Linux In The Park

   It is about time to start planning this.
   
   - When :: TBD.  Perhaps mid-August.
   - Where :: The park off Dufferin from last year worked out fairly well
   - Publicity :: Need to start publicity much earlier than last year
   
** Systems

*** Web Sites

**** Main web site

Seems to be working fine

**** Mediawiki

Offline.

We were planning to put a ~wget~ of it into a git repo to at least have a static copy available.

**** Trac

Offline.

That's where board meeting notes are, and, it being offline, we haven't got notes terribly readily available.

A ~wget~ of it would be _super_ useful.

*** Mailing Lists

Need to understand what the status is of what is currently running, and where it's running.

**** Yahoo!

It's possible that we need to prevent Yahoo! subscribers from sending messages to the list.
[[http://emailskinny.com/2014/04/07/yahoo-mail-brings-the-pain-with-dmarc-policy-change/][Yahoo Mail Brings the Pain with DMARC Policy Change]]


*** Git Hosting

- GitHub is okay for now but we need to move to a GTALUG owned host (hopefully when we get a new server).

- A couple of people should at least be backing up all the major repos.

- For material that is intended to be public, such as web site, it should be fine to use GitHub; for private material, that is unsuitable.

- Chris has some [[https://github.com/cbbrowne/slony-backups/tree/master/scripts][scripts he uses to manage Slony web site backups]] which actually does include encrypting (using GPG) some material (/e.g./ - lists of subscribers) that should be kept private.

**** gitolite

[[http://gitolite.com/gitolite/][gitolite]]

- Nothing cool, just access to Git repos though SSH and GitWeb.

- Easiest to maintain  :: ~apt-get install gitolite~ and you're done

- Harder to use :: To edit a Git repo it requires a SSH key

**** GitLab

[[https://www.gitlab.com/]]

- Enterprisey :: LDAP and A.D. support

- Easier to use (vs ~gitolite~) :: has a similar feature set to GitHub

- Harder to maintain :: looks like best to run in a Docker instances and has way too many dependencies

** CAG Report

** Bylaw Revisions

Chris: _I don't quite recall what was the state of things last month._

Myles: _I recall Bill saying that we just needed to submit the bylaws again (no changes necessary)._
