* 28th April, 2014

** Upcoming Meetings

- May ::  Movie Magic: The Art of Visual Effects with Ahmed Shehata 

- June :: TBA

- July :: Hopefully Drew and Scott on ~systemd~

*** Coordinator position

- Scott wants to step down from the coordinator position

- Coordinator needs to be at meetings :: Good idea to solicit from the list; Scott to do so

- Myles planning to solicit some Python folk

- Myles has an idea for later in the summer/fall

- DCB has a somewhat nontechnical talk he's thinking about

** Ryerson Logistics

The new room seems to be working fine thus far.

** Linux In The Park

   It is about time to start planning this.
   
   - When :: TBD.  Perhaps mid-August.
   - Where :: The park off Dufferin from last year worked out fairly well
   - Publicity :: Need to start publicity much earlier than last year
   
** Systems

*** Web Sites

**** Main web site

Seems to be working fine

**** Mediawiki

Offline.

We were planning to put a ~wget~ of it into a git repo to at least have a static copy available.

**** Trac

Offline.

That's where board meeting notes are, and, it being offline, we haven't got notes terribly readily available.

A ~wget~ of it would be _super_ useful.

*** Mailing Lists

Need to understand what the status is of what is currently running, and where it's running.

**** Yahoo!

It's possible that we need to prevent Yahoo! subscribers from sending messages to the list.
[[http://emailskinny.com/2014/04/07/yahoo-mail-brings-the-pain-with-dmarc-policy-change/][Yahoo Mail Brings the Pain with DMARC Policy Change]]


*** Git Hosting

- This isn't merely about hosting Git repos; it is about using those Git repos to store
  - Web site(s) :: /e.g./ - the main front page of [[gtalug.org]]
  - Board Notes :: /e.g./ - this very set of notes, which had been getting captured in a Trac repository
  - Replacement of Wiki infrastructure :: This is rather more debatable (/e.g./ We should have a debate about this!!!), but this may be a better way of capturing material (even of somewhat adhoc nature) that we used to capture in a MediaWiki instance.

- GitHub is okay for now but we need to move to a GTALUG owned host (hopefully when we get a new server).

- Multiple people should be backing up all the major repos

- For material that is intended to be public, such as web site, it should be fine to use GitHub; for private material, that is unsuitable.

- Chris has some [[https://github.com/cbbrowne/slony-backups/tree/master/scripts][scripts he uses to manage Slony web site backups]] which actually does include encrypting (using GPG) some material (/e.g./ - lists of subscribers) that should be kept private.

- Chris observes ... :: Managing this in a Git repo using the GitHub web interface is surprisingly usable.  This /is/ a good alternative to Trac for capturing board meeting notes.  I'm using [[http://orgmode.org/][Org Mode]], which I really like to use with Emacs.  It plays perfectly well with GitHub, as there are [[http://orgmode.org/worg/org-tools/index.html][various tools to manipulate Org data]] including some Ruby-based stuff that is used by GitHub.

**** gitolite

[[http://gitolite.com/gitolite/][gitolite]]

- Nothing cool, just access to Git repos though SSH and GitWeb.

- Easiest to maintain  :: ~apt-get install gitolite~ and you're done

- Harder to use :: To edit a Git repo it requires a SSH key

**** GitLab

[[https://www.gitlab.com/]]

- Enterprisey :: LDAP and A.D. support

- Easier to use (vs ~gitolite~) :: has a similar feature set to GitHub

- Harder to maintain :: looks like best to run in a Docker instances and has way too many dependencies

** CAG Report

** Bylaw Revisions

Chris: _I don't quite recall what was the state of things last month._

Myles: _I recall Bill saying that we just needed to submit the bylaws again (no changes necessary)._
