name: 'GTALUG Board'
site_url: 'http://board.gtalug.org'
permalink: /:year-:month-:day/:title.html

source: .
destination: ./_site

highlighter: false

exclude: ['fabfile.py', 'fabfile.pyc', 'Gemfile', 'README.md']

prose:
  rooturl: '_posts'
  siteurl: 'http://board.gtalug.org/'
  relativeLinks: 'http://board.gtalug.org/links.jsonp'
  media: media
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "select"
          label: "Select Title"
          placeholder: "Agenda/Meeting Notes"
          options:
            - name: "Agenda"
              value: "Agenda"
            - name: "Meeting Notes"
              value: "Meeting Notes"
