---
layout: post
title: "Agenda"
published: true
---

* 19 November 2018 at 7:30pm

** Location

- Hacklab

** Agenda Topics
 - Timing/Location of next Ops meeting
 - Upcoming Meetings
 - ICANN material
 - FSOSS followup
 - Social media
   - Any more youtube comments?
   - Should we remove old community announcements and publish announcements in the future?
   - Talk thumbnails
        - Are they better than just a random image?
        - Which style should we use? (logo, no logo, outline thickness, how to summarize the topic, shoudl we include speaker name?)
 - Verify site on youtube (needs dns registration) https://www.youtube.com/advanced_settings
 - Write next month's agenda.

** TODO from last month
  - TODO Alex :: Upgrade penguin to next Debian version so we can have Ruby 2.5 and such
  - TODO Scott :: Send out publicity for FSOSS call for speakers encouraging our involvement
    - Evan has a contact for this, Catherine Leung
  - TODO Alex :: Thumbnail for YouTube for Alex
  - TODO Scott :: What to do about Google Adwords
  - TODO Alex :: Drop G+ reference on GTALUG front page
  - TODO Gord :: Prep an ICANN presentation some time, not necessarily before 2019
  - TODO Alex :: presentation on systems and/or video deployment
  - TODO Chris :: Turn on DNSSEC for gtalug.org
