---
layout: post
title: "Agenda"
published: true
---

* 19 November 2018 at 7:30pm

** Location

- Hacklab

** Agenda Topics
 - Timing/Location of next Ops meeting
 - Upcoming Meetings
 - ICANN material
 - FSOSS followup
 - Social media
    - Any more youtube comments?
    - Should we remove old community announcements and publish announcements in the future?
    - Makerfest videos.
      - We should keep them, but we never discussed if we should do something like that again in the future
    - Talk thumbnails
      - Are they better than just a random image?
      - Which style should we use? (logo, no logo, outline thickness, how to summarize the topic, should we include speaker name?).
    - Should we discuss the format that we are using to post videos (separate talk and Q&A sections?).
      - Should we formalize & document the formats we're posting videos, so the speakers know in advance what to expect.
      - lightning talk and short videos (under 30 minutes) are posted as one video, when posting on the website we post the whole playlist for that meeting.
      - How we should handle this on other social media (mastodon, twitter)? Post entire playlist, or one post per video?
      - For lightning talks, should we post all videos at once, or as we get releases or a video per day?

 - Verify site on youtube (needs dns registration) https://www.youtube.com/advanced_settings
 - Invite more women speakers.
 - Discuss getting new people from meetup, cost is [6 months for US$14.99 / month ($119.18 CAD)]
 - Write next month's agenda.
** TODO from last month
  - TODO Alex :: Upgrade penguin to next Debian version so we can have Ruby 2.5 and such
    - automatic deployment under way
    - still an ~apt-get~ upgrade to complete
  - DONE Scott :: Send out publicity for FSOSS call for speakers encouraging our involvement
    - Evan has a contact for this, Catherine Leung
  - DONE Alex :: Thumbnail for YouTube for Alex
  - TODO Scott :: What to do about Google Adwords
  - DONE Alex :: Drop G+ reference on GTALUG front page
  - TODO Gord :: Prep an ICANN presentation some time, not necessarily before 2019
  - TODO Alex :: presentation on systems and/or video deployment
  - DONE Chris :: Turn on DNSSEC for gtalug.org

